Add follow me support for Breez Max
bodyscape/cielo_home pull request #38
Opened 2023-11-11 06:22 UTC by mikeyoon

Adds support for the follow me feature. One thing I noticed that might need addressing is that I restricted it to the Breez Max. I don't know if this feature is limited to the Max, or if there's a better way to determine follow me compatibility altogether.

2023-11-12 16:16 UTC, miles267 commented
Thanks @mikeyoon. Am so excited to use this on my Breez Max. I’ve found the temp reading at the main air handler up high on wall to read differently than on wall where the BM thermostat is installed. How can we start using this new feature?

2023-11-12 16:45 UTC, bodyscape requested changes

2023-11-12 16:45 UTC, bodyscape commented on custom_components/cielo_home/cielohomedevice.py
> +            "followme": self._device["latestAction"]["followme"],
Put this in a try exception. Not all device has this feature

2023-11-12 16:47 UTC, bodyscape commented on custom_components/cielo_home/switch.py
> +        if device.get_device_type() == "BREEZ-MAX":
you must check if the device is support follow-me, not if it's Breeze max. My device support it and i don't have a Breeze-Max.

2023-11-14 18:24 UTC, audreez commented
are you guys sure only max supports follow me ?

i have breez-plus and breez-eco and they both allow me to use follow me function which changes the temp on midea, can these be added?

2023-11-14 18:27 UTC, bodyscape commented
Don't worry, i ask for he change that! It's not for only the breeze-max

2023-11-29 13:34 UTC, merged